racaljk/hosts

README.md

gedit is a GUI application, and GUI applications should use gksudo because of config path, etc.

Use gksudo

---

hosts

Google.cn不需翻墙，所以无需使用国外源代理
打开Google.cn的翻译和地图，明显速度有很大提升
C:\Users\Administrator>ping translate.google.cn
正在 Ping translate.google.cn [203.208.50.134] 具有 32 字节的数据:
来自 203.208.50.134 的回复: 字节=32 时间=26ms TTL=127
来自 203.208.50.134 的回复: 字节=32 时间=27ms TTL=127
来自 203.208.50.134 的回复: 字节=32 时间=26ms TTL=127
来自 203.208.50.134 的回复: 字节=32 时间=29ms TTL=127
203.208.50.134 的 Ping 统计信息:
数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
最短 = 26ms，最长 = 29ms，平均 = 27ms

hosts: 更换Google.cn为国内IP，优化Twitter相关服务连接

---

hosts_tools/scripts/script_tool_for_windows.bat

The bat before just open hosts in notepad with administrator privilege
so the user have to copy the content by themselves.

自动拷贝hosts到Windows的etc目录下，并增加自动备份功能

---

hosts

Fix Drive Notepad for Google drive. Drive Notepad is to edit the text files in your Google drive online.

Fix DriveNotepad for Gdrive

---

hosts

解决flickr不能下载的问题，添加了downloadr.flickr.com的地址

解决flickr不能下载的问题

---

hosts

Try commit again to fix the format issue.
Added some hosts of Line. The customer from one of the projects in Korean requires me to have Line installed for daily communications, unfortunately I just found it had been banned by GFW long ago...tried to add some hosts to make it work.
Please deny my PR if the project owner consider this is not that useful...honestly I have no idea that how many people are still using Line in China mainland...

Hosts Added: Line Hosts

---

hosts

I am terribly sorry that I have to remove the hosts of LINE which I committed yesterday...found that simply adding hosts for it doesn't really help, any LINE ID associated with the phone numbers of China mainland, HK, Japan can not work properly in China mainland (even you could login and get connected, but you could not receive any message/update/invitation, etc.)...Hosts change won't solve the issue...it requires other tweaks instead.
Sorry again for the inconvenience.

REMOVED: hosts of LINE

---

hosts

www.w3schools.com 上不去，把它前面的注释符号去掉

W3Schools 上不去，应该加回来

---

hosts

今天下载谷歌地球发现 dl.google.com无法访问，查看hosts文件发现被注释了

Reset  dl.google.com

---

hosts

用于下载账户归档文件。
详见https://myaccount.google.com/privacy#takeout

Add takeout.google.com

---

hosts

修復谷歌學術導入、引用。
為什麼不用220.255.2.153？因為測試這個域名用了直接403

Add scholar.googleusercontent.com

---

hosts

另外发现一个clientauthconfig.clients6.google.com，但暂时未找到可用IP

Add iam.clients6.google.com

---

hosts

Today I visit Google as usual, but it automatically jump to an address, but it seems walled. I tried to add it on my local PC and enter the page.  (snapshot is below). So I come back to add a host.
---Snapshot: https://raw.githubusercontent.com/HzDSN/MyFirstProject/master/Add-ipv4.google.com.png

Add ipv4.google.com

---

hosts

之前的hosts会导致
安卓上onedrive客户端
在有Wifi或4G的时候检测不到网络
不能同步
注释掉之后可以成功同步

cancel onedrive hosts (取消掉onedrive的hosts)

---

README.md

Wikiwand using ajax.googleapis.com, open this link:
http://www.wikiwand.com/zh/Hosts%E6%96%87%E4%BB%B6#/.E6.96.87.E4.BB.B6.E4.BD.8D.E7.BD.AE.E5.8F.8A.E9.BB.98.E8.AE.A4.E5.86.85.E5.AE.B9
it will lead to ajax.googleapis.com opened by HTTP, so change this link to HTTPS.

fix wikiwand in README.md

---

hosts

郁闷死我了. 没想到 一个月 不能玩的英国游戏 Robocraft, 居然是 aws 引起的. 难道是 英国脱欧的后遗症 (服务器在 London)?

Fix aws, then fix Robocraft can't be played BTW.

---

hosts

1. Battle.net works fine now. No need to be redirected anymore.
2. Some domains of box.com can be resolved correctly. So deleted them.
3. Replaced some ips used for dropbox.com by official ones.
4. Twitter: Deleted some NX domains and added some. Deleted tinypic.com & twimg.co because they can be correctly resolved.
5. Google: Deleted books, video, orkut, HK plus and some l.google (NX) domains. Keyhole service (kh, khm, khmdb) and some pagead services are redirected to Google China, so deleted either.

Multiple Updates

---

tools/lhosts

您好，增加了自动保留首次使用时候的内容，无需注意首次使用范围模式。
并测试通过。
您可于查看代码修改之后，通过
`curl https://raw.githubusercontent.com/clh021/hosts/master/tools/lhosts | sh`
先行测试。
实现原理：当检查到是首次运行时，自动添加范围标签。

首次使用时将自动保留原hosts内容，无需注意是否首次，是否需要范围模式

---

hosts

Redirecting to 'events.google.com'.

add 'savethedate.foo' for Google I/O 2017

---

hosts

'tools.android.com' no longer provides downloads for Android Studio.

Add 'androidstudio.googleblog.com' for new release updates.

---

hosts

Remove "tensorflow.googlesource.com" since this project is now hosted on GitHub.
Update IP address for "www.tensorflow.org".
Fix #1029.

Fix TensorFlow.

---

tools/lhosts

修正lhosts脚本中sed命令在Mac下抛异常的bug。
抛出的异常内容：sed: 1: "1 i\# 远程 hosts 开? ...": extra characters after \ at the end of i command

修正lhosts脚本中sed命令在Mac下抛异常的bug

---

hosts.yml

add Resilio Sync
解决 Resilio Sync 软件无法获取追踪器列表的问题

add Resilio Sync
