- hosts
> 增加go.googlesource.com

- hosts
> 增加 www.gravatar.com

- hosts
增加google-code-prettify.googlecode.com
> 增加google-code-prettify.googlecode.com

- README.md
- hosts
需要访问Twitter的，请使用移动版https://mobile.twitter.com
> 更新Steam商店IP，支持更多谷歌新服务

- README.md
具体请看commit的内容。另外那个./hosts/hosts_tool中的script_tool_for_linux.bash写的够不规范的……一条wget就够了。
> 更改README中的几个小地方并推荐在*nix系统中使用命令。

- hosts
> 添加遗漏的个人信息与隐私设置页面

- README.md
> change about Linux restart network connection

- hosts
> Add Travis CI Fastly CDN

- hosts_tool/custom
- hosts_tool/script_tool_for_linux.bash
主要是以下更改：
- 增加了按目前时间命名备份的功能，这样看起来更清楚；
- 增加了自定义不变的、个人专属的 hosts 内容，放在 `custom` 文件中，用户可自行修改；
- 运行前就强制要求 root 权限，避免事情做到一半才发现有问题。
这个项目做得很好，希望以后 hosts 能继续保持更新。
学生党么？万岁！
> 增强了 linux 下 bash 脚本的功能

- hosts
Found unblocked Twitter IP, hosts file updated. Other Twitter IPs (img, videos etc.) seems unaffected.
> Twitter fixed

- README.md
> just a little change.

- hosts
以及
注释了一些使用GoogleCN
注释了一些IP没有被墙的
还有就是是否要添加License？如果要的话我再Push，建议使用CC 4.0 BY-NC-SA
> hosts:修复ghs & 增加W3schools & 删除无效记录

- README.md
推荐改host修改工具[Gas Mask](http://www.macupdate.com/app/mac/29949/gas-mask/)
> Mac tool introduce

- hosts
Maybe faster
test by "UsbEAm Hosts Editor v2.1"
> Change Steam IP 103.* to 203.*

- README.md
> Let our README be clear and simple.

- HostsTool/HostsGeter.bat
添加了hostsgeter,hostsgeter是一个方便的hosts更新工具
主要特性
1.自动从Github下载hosts
2.替换hosts
3.备份hosts
> HostsGeter Pull

- hosts_tools/scripts/script_tool_for_windows.bat
改进 @lizongzeshunshun 的`HostsGeter.bat`脚本。
主要改进：
1. 增加临时脚本日志
2. 增加错误提示
3. hosts 备份文件名格式改为 `hosts+随机数字` （避免因日期包含`/`而备份失败）
> 魔改 HostsGeter.bat

- hosts_tools/HostsToolforMac/README.md
https://github.com/ZzzM/HostToolforMac
> add Source Code link

- hosts
> Add security.googleblog.com

- hosts
Add gmail/chrome/search/webmasters/maps/cloudplatform/youtube.googleblog.com
> Add some googleblog

- hosts_tools/scripts/script_tool_for_linux.sh
modified:   hosts_tools/scripts/script_tool_for_linux.sh
> Changes to be committed:

- hosts_tools/HostsToolforWindows/README.md
- hosts_tools/HostsToolforWindows/download.hpp
- hosts_tools/HostsToolforWindows/hosts_tool.cpp
- hosts_tools/README.md
> Fix fatal bug for windows console hosts tool.

- hosts
> Repair gmail imap/pop

- hosts_tools/HostsToolforWindows/README.md
- hosts_tools/HostsToolforWindows/hosts_tool.cpp
- hosts_tools/HostsToolforWindows/mitlicense.hpp
- hosts_tools/README.md
Task list:
Thanks to @qwerty258 .
> Windows console hosts tool Important update

- hosts_tools/HostsToolforWindows/README.md
- hosts_tools/HostsToolforWindows/diff.hpp
- hosts_tools/HostsToolforWindows/download.hpp
- hosts_tools/HostsToolforWindows/hosts_tool.cpp
- Fix bug of try {...} catch{...}
- Fix the bug of `CloseServiceHandle()` in exit program
- Separate function `Func_CheckDiff()`
- Fix the bug of check failed.
BTW:我从网页版直接下载zip后得到的源代码是windows的换行符而不是unix的换行符 这个是网页版的锅 @andytimes @imcaffrey
> Fix little bug of Hosts Tool for Windows Console

- hosts_tools/HostsToolforWindows/hosts_tool.cpp
The updates are as follows:
- Little bug fixed.(Debug mode)
- Increased help content.
> Update of Hosts Tool for Windows Console

- .github/ISSUE_TEMPLATE.md
- README.md
> Add YouTube issue link in README.md and issue template.

- hosts
Add commondatastorage.googleapis.com;ghs-svc-https-c1196.ghs-ssl.googlehosted.com;ghs.googlehosted.com
> Fix #395 #396

- hosts
> Fix Soundcloud #401

- hosts
\>psping 64.233.171.192:7276
TCP connect to 64.233.171.192:7276:
5 iterations (warmup 1) connecting test:
Connecting to 64.233.171.192:7276 (warmup): 224.62ms
Connecting to 64.233.171.192:7276: 224.72ms
Connecting to 64.233.171.192:7276: 224.53ms
Connecting to 64.233.171.192:7276: 224.11ms
Connecting to 64.233.171.192:7276: 225.17ms
TCP connect statistics for 64.233.171.192:7276:
Sent = 4, Received = 4, Lost = 0 (0% loss),
Minimum = 224.11ms, Maximum = 225.17ms, Average = 224.63ms
> Fix supl.google.com #349

- hosts
> Add domains.google & www.registry.google according to #410

- README.md
> Chage doodle to a lovely one

- hosts
> wiki for mobile

- hosts
> add spaces.google.com and vr.google.com

- hosts
Added a bunch of Tumblr hosts which work for both browser and client.
The first 9 lines leveraged from the contribution of @laodcn
> Add some hosts for Tumblr

- hosts
> add Android Developers Blog

- hosts
> Add Google Material Design Guidelines site(#471)

- hosts
> add 'android-developers.blogspot.hk'

- hosts
> Add Chrome HSTS Preload Submission

- hosts
Google推出了新版的Web字体网站Google Fonts
> Add Google Fonts

- hosts
> 修復Instagram

- hosts
> add some google blog

- hosts
> add 'firebase.google.com'

- hosts
> add apkpure.com

- hosts
> add Google Contributor License Agreement

- hosts
> update IP of gist.github.com to 192.30.253.119

- hosts
Google: Girls start out with a love of science and technology, but lose it somewhere along the way. Let’s help encourage that passion.
> Google: Less than 1% of girls study Computer Science. Let’s change that.

- hosts
> add apps.twitter.com

- hosts
> Add Google Fit

- hosts
Add Google Analytics 360 & Add Disqus
> Add Google Analytics 360 & Add Disqus

- README.md
Change http://i.imgur.com/* to https://i.imgur.com/*
(@beyondroot mentioned in #545 )
> Change http://i.imgur.com/* to https://i.imgur.com/* in README.md

- hosts
add myactivity.google.com such as https://myactivity.google.com/myactivity?hl=zh-CN&fg=1
> fix w3schools

- hosts
Show and post commits at the bottom of the APKPure page.
> add Disqus for APKPure

- hosts
> Add *.withgoogle.com

- hosts
> Fix network packet loss  when syncing the git repository on github.com

- README.md
> Add a link to "Things about China's internet"

- hosts
> Add Google fuchsia Git repositories

- hosts
> Repair Internet Archive

- hosts
- [. ] 没有无用commit（向Git仓库引入奇怪的东西）
- [. ] 确认更新有效以及更新的来源并遵守相关许可协议
- [. ] 部分Hosts Tool的问题请及时与相关作者联系
- [. ] hosts文件中ip与域名间是用`	`分隔而不是空格
- [. ] 更新hosts文件后请及时修改更新时间
> google.golang.org

- hosts
> add 'd.android.com', the same as 'dev.android.com'

- hosts
> Add linux.dropbox.com

- hosts
update google duo hosts with right ip
> update google duo hosts with right ip

- hosts
> Fixed Tumblr Issue

- hosts
> Fix format error

- hosts
> Add macos.telegram.org

- hosts
add codelabs.developers.google.com
> Update hosts add codelabs.developers.google.com

- hosts
> 修复 推特(Twitter)

- hosts
- a.android.com
- m.android.com
- r.android.com
> add some android dev short urls

- tools/hosts-hiwifi.sh
- 脚本适用于安装了自定义hosts插件的极路由
- 可以自动更新hosts
- 在自用设备部署已经两个月，使用正常
> added hosts-tool for hiwifi router

- hosts
> Add pixel.google.com

- hosts
https://github.com/racaljk/hosts/issues/633
> Add dartpad.dartlang.org

- hosts
> en.wikipedia.org

- hosts
> Add Google Research Blog

- hosts
add iTunes hosts to resolve DNS hijacking in China, like this:
```
iTunes 无法验证服务器“s.mzstatic.com.”的身份。此服务器的证书无效。您可能正在连接一个假装是“s.mzstatic.com.”的服务器，您的机密信息可能会有风险。您仍想连接该服务器吗？
```
> add iTunes hosts

- hosts
> Add Yahoo Finance

- hosts
tcping t.co 443
PING 185.45.5.36:443
response from 185.45.5.36:443, seq=0 time=176.51 ms
response from 185.45.5.36:443, seq=1 time=238.53 ms
response from 185.45.5.36:443, seq=2 time=230.68 ms
response from 185.45.5.36:443, seq=3 time=174.10 ms
response from 185.45.5.36:443, seq=4 time=173.84 ms
--- 185.45.5.36:443 ping statistics ---
5 responses, 5 ok, 0.00% failed
round-trip min/avg/max = 173.8/198.7/238.5 ms
> fix t.co #609

- hosts
> Fix Tumblr image

- hosts
大部分 都可以 直接连通. 指定了 ip 之后, 有时候会减速, 有时候会失效. 
github 下载未实质提升, 所以 先移除掉. #655 #503 #170 #101
> remove Amazon AWS

- hosts
> 添加谷歌服务支持域名

- hosts
As captioned, enjoy the holiday!
> Updated a few IP of Tumblr, for the reason you all know.

- hosts
> add madeby.google.com

- hosts
> Add Google G Suite

- hosts
> Fixed the facebook profile picture doesn't show up issue.

- hosts
> Add Google Assistant and Google Public DNS

- hosts
As captioned, fixed issue #682.
You'll love this fix...lol
> Fixed the tumblr media not playing issue (#682)

- hosts
> Add Google Cloud Status Dashboard

- hosts
> fix flickr images

- hosts
> Add armorgames.com.

- hosts
Update ajax.google.com, fixes #719.
Add domains for Google Analytics.
> Multiple updates for Google.

- hosts
Remove domains as @andytimes suggested in #720.
Add google-analytics.com.
> Update domains for Google Analytics.

- hosts
> Add Google ATAP

- hosts
1. Fix get.google.com mentioned in #725 ;
2. Fix Medium mobile's login issue mentioned in #724 ;
3. Fix Chrome mobile's news recommendation couldn't be loaded;
4. Clean wordpress & gravatar and add some.
> Additions & Fixes

- hosts
> Fix Twitter

- hosts
> Add WikiLeaks.

- hosts
> Add Google Patents and Google ISP

- hosts
Verified from 2 ISPs in CA, 4 ISPs in BJ.
> update Gravatar to working IPs

- hosts
详见https://github.com/racaljk/hosts/issues/812
> add bandwagonhost.com

- hosts
> Add Google Spaces  Fix onedrive

- hosts
clouderrorreporting.clients6.google.com
datastore.clients6.google.com
ssh.cloud.google.com
> Fixed google cloud platform

- hosts
- [ OK] 没有无用commit（向Git仓库引入奇怪的东西）
- [ OK] 确认更新有效以及更新的来源并遵守相关许可协议
- [OK] hosts文件中ip与域名间是用`	`(Tab)分隔而不是空格
- [OK] 更新hosts文件后请及时修改更新时间
> Add artsandculture.google.com domain

- hosts
> Add Google classroom

- hosts
> Add music-pa.clients6.google.com

- hosts
> Add psiphon.ca, psiphon3.com, torproject.org.

- hosts
fix issue https://github.com/racaljk/hosts/issues/887
> fix tumblr video

- hosts
> Update domains for DuckDuckGo.

- hosts
> Update invalid ip for google.

- hosts
*.xx.fbcdn.net域名包含Facebook视频、图片、CSS等...
> Fix Facebook

- hosts
> Added: chromedriver.storage.googleapis.com

- hosts
> remove google ip 64.233.162.83

- hosts
fix https://github.com/racaljk/hosts/issues/978
> add fonts.gstatic.com

- hosts
> Add pcbeta.com and xboxlive.com.

- hosts
> Google 本地向导

- hosts
> Perfection pinterest

- hosts
> add cloudnext.withgoogle.com site

- hosts
> Added *.web.telegram.org

- hosts
A domain which will be accessed to check internet access when Wi-Fi connected. Android 7.1.1
> add connectivitycheck.gstatic.com

- hosts
> fix Flickr

- hosts
> Add issue tracker for Android O

- hosts
> Add play-music.gstatic.com.

- hosts
* the website served as a tool to create missions in ingress
> Add mission-author-dot-betaspike.appspot.com

- hosts
Fetch from https://developers.google.com/
> Add: google official firebase blog

- hosts
* servers to store videos are different from that of *.twimg.com
> Modified video.twimg.com

- hosts
> add summer of code with google support

- hosts
Google is ur friend, and Google is our friend.
> Add: Google Open Souce Today~

- hosts
> Add some google sites fetched from opensource.google.com

- hosts
> Add some googlecode sites

- hosts
> Add: missing Google IO 2017 events host

- hosts
* add support for Google Developers
> Add google-developers.appspot.com

- hosts
* the domain is related to twitter settings
> Add hca.twimg.com

- hosts
* add caps.twitter.com
* add pbs-h2.twimg.com
> Add support for iOS app of twitter

- hosts
* add embed.culturalspot.org for Google Art & Culture
* add www.autodraw.com for AutoDraw project
> Add support for Google A&C and AutoDraw

- hosts
> fix www.panoramio.com

- hosts
with US, HK, Taiwan branch location
- 
没有无用commit（向Git仓库引入奇怪的东西）
- [ x] 确认更新有效以及更新的来源并遵守相关许可协议
- [ x] 部分Hosts Tool的问题请及时与相关作者联系
- [ x] hosts文件中ip与域名间是用`	`(Tab)分隔而不是空格
- [ x] 更新hosts文件后请及时修改更新时间
> Added thebodyshop

- hosts
> _(•̀ω•́ 」∠)_

- hosts
Added some new YouTube domains.
> Add Several YouTube Domains

- hosts
go get will connect code.googlesource.com for git to download code
> add code.googlesource.com for go

- tools/README.md
> Added Daedalus to tools/README. Close #1115

- hosts
> Fix coursera.org videos

- hosts
> Fix twitter and panoramio

- hosts
https://androidstudio.googleblog.com/2017/05/android-studio-30-canary-1-sdk-updates.html
> Add Google io 2017 android lib new repo

- hosts.yml
> Add support for Google Photos on iOS device

- hosts.yml
> Add scontent.facebook.com

- hosts.yml
* add device-provisioning.googleapis.com
> Add support for Goolgle iOS apps

- hosts.yml
> 增加AWS香港节点IP

- hosts.yml
> modify Resilio Sync

- hosts.yml
> Add GitHub CDN

- hosts.yml
fix onedrive mapping, tested and it works in Shanghai Telecom.
Please refer to : https://www.v2ex.com/t/369807
> fix onedrive

- hosts
203.84.197.27 hk.finance.yahoo.com0  >>   203.84.197.27
hk.finance.yahoo.com
> fix line 3921

- hosts.yml
hk.finance.yahoo.com0 >>hk.finance.yahoo.com
这次应该对了
> fix hosts.yml line 4487
